default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # w/o Docker
  username: root
  password:
  socket: /tmp/mysql.sock
  # w/ Docker
  # username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  # password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  # host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: memorization_app_development

test:
  <<: *default
  database: memorization_app_test

production:
  <<: *default
  database: memorization_app_production
  # username: memorization_app
  # password: <%= ENV['MEMORIZATION_APP_DATABASE_PASSWORD'] %>
